### ISSUE TITLE
Can not download book anymore

### ISSUE THREAD

**Issue by bvhpro** [kennedyoliveira/alfred-it-ebooks#1]
Can not download book anymore
all link was death :(

[http://it-ebooks.top](http://it-ebooks.top)

**Comment by kennedyoliveira** [comment]
Hello @bvhpro omg i didn't know someone was using it haha, it's a work in progress, you shouldn't be using, and i stopped working on it when i started haha, due to shift of priority, i plan to finish it, but not now, and i didn't know it's working too o_O.

Anyway, the links are dead because the site is with downloads disabled as you can see:
![it_ebooks_-_free_download_-_big_library](https://cloud.githubusercontent.com/assets/7723330/19413477/a9a39bd8-9304-11e6-9856-f68e22dd39d5.png)

**Comment by kennedyoliveira** [comment]
I'm closing the issue, if you need anything else, please open another issue.
